#!/usr/bin/env bash
# ollama_autoconfig.sh — Detect host hardware and write optimal Ollama configuration.
# Outputs: ~/.ollama/config  and  .env (sourced by Makefile / systemd)
#
# Telemetry is always disabled.

set -euo pipefail

CONFIG_DIR="${HOME}/.ollama"
CONFIG_FILE="${CONFIG_DIR}/config"
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env"

mkdir -p "${CONFIG_DIR}"

# ---------- Detect RAM ----------
TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
TOTAL_RAM_MB=$((TOTAL_RAM_KB / 1024))
TOTAL_RAM_GB=$((TOTAL_RAM_MB / 1024))

echo "Detected RAM: ${TOTAL_RAM_GB} GB (${TOTAL_RAM_MB} MB)"

# How many models to keep loaded simultaneously
if [ "${TOTAL_RAM_GB}" -ge 16 ]; then
    MAX_LOADED_MODELS=3
    NUM_PARALLEL=4
elif [ "${TOTAL_RAM_GB}" -ge 8 ]; then
    MAX_LOADED_MODELS=2
    NUM_PARALLEL=2
else
    MAX_LOADED_MODELS=1
    NUM_PARALLEL=1
fi

# Context length: ~1 KB per token, budget 60% of RAM for context
CONTEXT_RAM_MB=$((TOTAL_RAM_MB * 60 / 100))
# Rough: 4 bytes per token, 1 token ≈ 4 bytes of KV cache at fp16 for small models
# Conservative: allow ~2KB per context token for overhead
CONTEXT_LENGTH=$((CONTEXT_RAM_MB * 512))
# Cap at reasonable maximums
if [ "${CONTEXT_LENGTH}" -gt 131072 ]; then
    CONTEXT_LENGTH=131072
fi
if [ "${CONTEXT_LENGTH}" -lt 2048 ]; then
    CONTEXT_LENGTH=2048
fi

# ---------- Detect CPU ----------
CPU_CORES=$(nproc 2>/dev/null || echo 4)
# Use 75% of cores for inference threads
NUM_THREADS=$((CPU_CORES * 3 / 4))
if [ "${NUM_THREADS}" -lt 1 ]; then
    NUM_THREADS=1
fi

echo "Detected CPU cores: ${CPU_CORES}, using ${NUM_THREADS} threads"

# ---------- Detect GPU ----------
GPU_LAYERS=0
GPU_TYPE="none"

if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
    GPU_TYPE="cuda"
    # Use all layers on GPU
    GPU_LAYERS=999
    echo "Detected GPU: NVIDIA (CUDA)"
elif [ -d /sys/class/kfd ] && [ -d /opt/rocm ] 2>/dev/null; then
    GPU_TYPE="rocm"
    GPU_LAYERS=999
    echo "Detected GPU: AMD (ROCm)"
elif system_profiler SPDisplaysDataType 2>/dev/null | grep -q "Metal"; then
    GPU_TYPE="metal"
    GPU_LAYERS=999
    echo "Detected GPU: Apple Metal"
else
    echo "No GPU detected, using CPU only"
fi

# ---------- Write config ----------
cat > "${CONFIG_FILE}" <<EOF
# Auto-generated by ollama_autoconfig.sh — $(date -Iseconds)
# Hardware: ${TOTAL_RAM_GB}GB RAM, ${CPU_CORES} cores, GPU=${GPU_TYPE}
OLLAMA_MAX_LOADED_MODELS=${MAX_LOADED_MODELS}
OLLAMA_NUM_PARALLEL=${NUM_PARALLEL}
OLLAMA_NUM_THREADS=${NUM_THREADS}
OLLAMA_GPU_LAYERS=${GPU_LAYERS}
OLLAMA_CONTEXT_LENGTH=${CONTEXT_LENGTH}
OLLAMA_NOPRUNE=1
OLLAMA_NOTELEMETRY=1
EOF

echo "Wrote Ollama config to ${CONFIG_FILE}"

# ---------- Write .env ----------
cat > "${ENV_FILE}" <<EOF
# Auto-generated by ollama_autoconfig.sh — $(date -Iseconds)
export OLLAMA_MAX_LOADED_MODELS=${MAX_LOADED_MODELS}
export OLLAMA_NUM_PARALLEL=${NUM_PARALLEL}
export OLLAMA_NUM_THREADS=${NUM_THREADS}
export OLLAMA_GPU_LAYERS=${GPU_LAYERS}
export OLLAMA_CONTEXT_LENGTH=${CONTEXT_LENGTH}
export OLLAMA_NOPRUNE=1
export OLLAMA_NOTELEMETRY=1
export OLLAMA_HOST=127.0.0.1:11434

# HuggingFace telemetry off
export HF_HUB_DISABLE_TELEMETRY=1
export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1
export DO_NOT_TRACK=1
EOF

echo "Wrote .env to ${ENV_FILE}"
echo "Done. Source the .env or restart ollama to apply."
